// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package consul

import (
	"consul-cli/internal/client"
	"consul-cli/internal/server"
	"consul-cli/internal/service"
)

// Injectors from wire.go:

// initApp init consul application.
func InitApp() *app {
	clientClient := client.NewClient()
	consulCliService := service.NewConsulCliService(clientClient)
	engine := server.NewHTTPServer(consulCliService)
	consulApp := newApp(engine)
	return consulApp
}
